batch_size: 32
checkpoint_dir: checkpoints_t/new_t/20220214T072932421638-pushing_4-small_divider-ours-original-no-spatial-intent
checkpoint_freq: 1000
checkpoint_path: checkpoints_t/new_t/20220214T072932421638-pushing_4-small_divider-ours-original-no-spatial-intent/checkpoint_00304000_ddpg.pth.tar
checkpoints_dir: null
discount_factors:
- 0.85
distance_to_receptacle_map_scale: 0.25
env_name: small_divider
experiment_name: pushing_4-small_divider-ours-original-no-spatial-intent
exploration_frac: 0.1
final_exploration: 0.01
grad_norm_clipping: 100
inactivity_cutoff_per_robot: 100
intention_channel_encoding: spatial
intention_channel_nonspatial_scale: 0.025
intention_map_encoding: ramp
learning_rate: 0.025
learning_starts_frac: 0.001
lifting_pointless_drop_penalty: 0.25
log_dir: checkpoints_t/new_t/20220214T072932421638-pushing_4-small_divider-ours-original-no-spatial-intent
logs_dir: null
num_cubes: 10
num_input_channels: 4
obstacle_collision_penalty: 0.25
partial_rewards_scale: 2.0
policy_path: checkpoints_t/new_t/20220214T072932421638-pushing_4-small_divider-ours-original-no-spatial-intent/policy_00304000_ddpg.pth.tar
random_seed: null
replay_buffer_size: 10000
robot_collision_penalty: 1.0
robot_config:
-   pushing_robot: 4
room_length: 1.0
room_width: 0.5
run_name: 20220214T072932421638-pushing_4-small_divider-ours-original-no-spatial-intent
shortest_path_map_scale: 0.25
show_gui: false
success_reward: 1.0
target_update_freq: 1000
total_timesteps: 340000
train_freq: 4
use_closest_cube_map: false
use_distance_to_receptacle_map: false
use_double_dqn: true
use_egl_renderer: true
use_history_map: false
use_intention_channels: false
use_intention_map: false
use_partial_observations: true
use_predicted_intention: false
use_predicted_intention_frac: 0.9
use_reward_for_closest_cube: false
use_shortest_path_map: true
use_shortest_path_movement: true
use_shortest_path_partial_rewards: true
use_shortest_path_to_receptacle_map: true
weight_decay: 0.0001
